version: "2"
services:
  irishub-server:
    image: irisnet/irishub-sync:develop
    container_name: c-irishub-sync-develop
    volumes:
      - /mnt/data/irishub-sync/log:/irishub-sync/log
    environment:
      ENV: dev
      DB_ADDR: 192.168.150.7:30000
      DB_USER: iris
      DB_PASSWD: irispassword
      DB_DATABASE: sync-iris


      SER_BC_NODE_URL: tcp://192.168.150.7:26657
      SER_BC_CHAIN_ID: rainbow-dev
      SER_BC_TOKEN: iris
      SER_MAX_GOROUTINE: 60
      SER_SYNC_BLOCK_NUM: 8000

      LOG_FILE_PATH: /irishub-sync/log/sync_server.log
      LOG_FILE_MAX_SIZE: 200
      LOG_FILE_MAX_AGE: 7
      ENABLE_ATOMIC_LEVEL: true
      LOG_COMPRESS: true
